services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    networks:
      - webnet

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - .env
    networks:
      - webnet

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

