name: Lab7 CI
on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'backend') || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Build backend image
        run: |
          cd spring-backend
          docker build -t my-backend:${{ github.sha }} .

  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'frontend') || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Build frontend image
        run: |
          cd react-frontend
          docker build --build-arg REACT_APP_API_BASE_URL=/api/v1 -t my-frontend:${{ github.sha }} .

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run backend tests
        run: |
          cd spring-backend
          mvn test -q

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run frontend tests
        run: |
          cd react-frontend
          yarn install --frozen-lockfile
          yarn test --ci --coverage=false

  deploy:
    needs: [build-backend, build-frontend, test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d

