name: Lab7 CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test Both
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend image
        run: |
          docker build \
            -f backend.Dockerfile \
            . \
            -t my-backend:${{ github.sha }}

      - name: Run backend tests
        run: |
          cd spring-backend
          mvn test -q

      - name: Build frontend image
        run: |
          docker build \
            -f frontend.Dockerfile \
            . \
            --build-arg REACT_APP_API_BASE_URL=/api/v1 \
            -t my-frontend:${{ github.sha }}

      - name: Run frontend tests
        run: |
          cd react-frontend
          yarn install --frozen-lockfile
          yarn test --ci --coverage=false

  deploy:
    name: Deploy via docker-compose
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull images & bring up
        run: |
          docker-compose pull
          docker-compose up -d
