name: Lab7 CI

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build & test backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, 'backend')
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build spring-backend -t my-backend:${{ github.sha }}

      - name: Run backend tests
        run: |
          cd spring-backend
          mvn test -q

  build-frontend:
    name: Build & test frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, 'frontend')
    steps:
      - uses: actions/checkout@v3

      - name: Build frontend Docker image
        run: |
          docker build react-frontend \
            --build-arg REACT_APP_API_BASE_URL=/api/v1 \
            -t my-frontend:${{ github.sha }}

      - name: Run frontend tests
        run: |
          cd react-frontend
          yarn install --frozen-lockfile
          yarn test --ci --coverage=false

  deploy:
    name: Deploy with Docker Compose
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Pull & restart services
        run: |
          docker-compose pull
          docker-compose up -d
