name: Lab7 CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Run Backend Tests
        run: mvn test

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: react-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js 16

